version: "3.9"
services:
  sv_web_exam:
    container_name: web_exam
    image: httpd
    depends_on:
      - sv_db_exam
    restart: always
    volumes:
      - ./frontend:/usr/local/apache2/htdocs
    ports:
      - "8081:80"

  sv_web_back_exam:
    container_name: web_back_exam
    image: node:16
    depends_on:
      - sv_db_exam
    restart: always
    volumes:
      - ./backend:/usr/src/app
    working_dir: /usr/src/app
    links:
      - "sv_db_exam:db"
    command: bash -c "npm i && npm install nodemon && npm install express && npm start"
    ports:
      - "8082:80"

  sv_db_exam:
    image: mysql:5.6
    volumes:
      - ./mysql-backup/:/var/lib/mysql
    container_name: db_exam
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: janista
      MYSQL_DATABASE: 0030_Lab_Exam
      MYSQL_PASSWORD: mypassword

    ports:
      - "3306:3306"
